name: deploy-to-pickerS3

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: git clone
        uses: actions/checkout@v2

      # - name: npm install for eslint
      #   run: npm install

      - name: npm install
        run: npm install
        working-directory: ./client

      - name: build
        env:
          REACT_APP_KAKAO_SEARCH: ${{ secrets.REACT_APP_KAKAO_SEARCH }}
          REACT_APP_KAKAO_API: ${{ secrets.REACT_APP_KAKAO_API }}
        run: CI='' npm run build
        # working-directory: ./cl

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_BUCKET_REGION }}
          SOURCE_DIR: '/home/runner/work/picker/picker/build'

      - name: 캐시 무효화
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_BUCKET_REGION }}
        run: aws cloudfront create-invalidation --distribution-id=E1V2Y0XAT8F2PB --paths "/*"
